
###
POST http://localhost:3969/api/v1/auth/registration
Content-Type: application/json

{     
    "name": "Admin",
    "email": "itsmeyoursujan@gmail.com",
    "contactNumber": "123456789",
    "password": "password123"
}


###
POST http://localhost:3969/api/v1/auth/registration
Content-Type: application/json

{     
    "name": "A B",
    "email": "test123@gmail.com",
    "contactNumber": "1233",
    "password": "password123"
}

# 
###
POST http://localhost:3969/api/v1/auth/login
Content-Type: application/json

{     
    "email": "test123@gmail.com",
    "password": "password123"
}

# LOGIN FOR ADMIN
###
POST http://localhost:3969/api/v1/auth/login
Content-Type: application/json

{     
    "email": "itsmeyoursujan@gmail.com",
    "password": "password123"
}

