GET http://localhost:3969/api/v1/fund/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdDk5cXdscDAwMDEyaXNxNjhqb2Vmb2UiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJzdXNwZW5kZWQiOmZhbHNlLCJpYXQiOjE3MDkzMzQ3MDQsImV4cCI6MTcwOTM3NzkwNH0.AS8NbcArq4j7yxHwQ6xIdLRuc0wM_U9thlln9PhbhqI

###
GET http://localhost:3969/api/v1/fund/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdDk5cXdscDAwMDEyaXNxNjhqb2Vmb2UiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJzdXNwZW5kZWQiOmZhbHNlLCJpYXQiOjE3MDkzMzQ3MDQsImV4cCI6MTcwOTM3NzkwNH0.AS8NbcArq4j7yxHwQ6xIdLRuc0wM_U9thlln9PhbhqI

###
POST http://localhost:3969/api/v1/fund/raise-fund
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdDk5cXYyMjAwMDAyaXNxcHdxbGprNWUiLCJlbWFpbCI6Iml0c21leW91cnN1amFuQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsInN1c3BlbmRlZCI6ZmFsc2UsImlhdCI6MTcwOTMzNDk3NCwiZXhwIjoxNzA5Mzc4MTc0fQ.St2H4RvYz9GxEEypN5A7ekAMGEDcnKiRbUcvHz28CTk

{
    "title":"Emergency Funding xitto3", 
    "equityPercentage":40, 
    "equityAmount":150000, 
    "description": "Full description about the company",
    "startDate":"2023-10-23", 
    "name":"Company Name", 
    "establishment": "2020-1-1", 
    "valuation": 100, 
    "panNumber": "12426724", 
    "companyDescription":"Company description",
    "endDate":"2024-2-2",
    "logo":"http://localhost",
    "document":"http://domain"

}

###
GET http://localhost:3969/api/v1/fund/get-my-fund
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdDk5cXdscDAwMDEyaXNxNjhqb2Vmb2UiLCJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJzdXNwZW5kZWQiOmZhbHNlLCJpYXQiOjE3MDkzNDk0MDcsImV4cCI6MTcwOTM5MjYwN30.CgJDhSYmjLViLnT_eossTdgF-eS18CuZfbxgfUe8OoE

###
DELETE http://localhost:3969/api/v1/delete-company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdDhtbXIzbDAwMDFpYTZ0cG5icHphbXkiLCJlbWFpbCI6Iml0c21leW91cnN1amFuQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsInN1c3BlbmRlZCI6ZmFsc2UsImlhdCI6MTcwOTMyMjM4NCwiZXhwIjoxNzA5MzY1NTg0fQ.o0PmDD4W8DEeqBgzYaolTvsHV2eHWF1iqRnInXc-lBw

{
    "panNumber":""
}